#       Makefile for SREC2BIN

PROJ=   srec2bin

CPP=    bcc
LINK=   tlink

CPU=3
BCC_MODEL=s

CFLAGS=/m$(BCC_MODEL) /K /f- /$(CPU) /w /a- $(CFLAGS) /c
LFLAGS=/LC:\BC5\LIB\ /x /Tde /$(CPU)

#-----------------------------------------------------------------------------

all:    $(PROJ).exe


.c.obj:
        $(CPP) $(CFLAGS) $<

OBJ = \
        $(PROJ).obj \


$(PROJ).exe: $(OBJ)
        $(LINK) $(LFLAGS) c0$(BCC_MODEL).obj $(OBJ), $(PROJ).exe, $(PROJ).map, c$(BCC_MODEL).lib

#-----------------------------------------------------------------------------

clean:
        -erase *.obj
        -erase $(PROJ).exe
